// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: info.proto

#include "info.pb.h"
#include "info.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace sysinfo {

static const char* SystemInfo_method_names[] = {
  "/sysinfo.SystemInfo/Processes",
};

std::unique_ptr< SystemInfo::Stub> SystemInfo::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SystemInfo::Stub> stub(new SystemInfo::Stub(channel, options));
  return stub;
}

SystemInfo::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Processes_(SystemInfo_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientWriter< ::sysinfo::Process>* SystemInfo::Stub::ProcessesRaw(::grpc::ClientContext* context, ::sysinfo::ServerResponse* response) {
  return ::grpc::internal::ClientWriterFactory< ::sysinfo::Process>::Create(channel_.get(), rpcmethod_Processes_, context, response);
}

void SystemInfo::Stub::async::Processes(::grpc::ClientContext* context, ::sysinfo::ServerResponse* response, ::grpc::ClientWriteReactor< ::sysinfo::Process>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::sysinfo::Process>::Create(stub_->channel_.get(), stub_->rpcmethod_Processes_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::sysinfo::Process>* SystemInfo::Stub::AsyncProcessesRaw(::grpc::ClientContext* context, ::sysinfo::ServerResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::sysinfo::Process>::Create(channel_.get(), cq, rpcmethod_Processes_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::sysinfo::Process>* SystemInfo::Stub::PrepareAsyncProcessesRaw(::grpc::ClientContext* context, ::sysinfo::ServerResponse* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::sysinfo::Process>::Create(channel_.get(), cq, rpcmethod_Processes_, context, response, false, nullptr);
}

SystemInfo::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SystemInfo_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< SystemInfo::Service, ::sysinfo::Process, ::sysinfo::ServerResponse>(
          [](SystemInfo::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::sysinfo::Process>* reader,
             ::sysinfo::ServerResponse* resp) {
               return service->Processes(ctx, reader, resp);
             }, this)));
}

SystemInfo::Service::~Service() {
}

::grpc::Status SystemInfo::Service::Processes(::grpc::ServerContext* context, ::grpc::ServerReader< ::sysinfo::Process>* reader, ::sysinfo::ServerResponse* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace sysinfo

