// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: info.proto
#ifndef GRPC_info_2eproto__INCLUDED
#define GRPC_info_2eproto__INCLUDED

#include "info.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace sysinfo {

class SystemInfo final {
 public:
  static constexpr char const* service_full_name() {
    return "sysinfo.SystemInfo";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientWriterInterface< ::sysinfo::Process>> Processes(::grpc::ClientContext* context, ::sysinfo::ServerResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::sysinfo::Process>>(ProcessesRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::sysinfo::Process>> AsyncProcesses(::grpc::ClientContext* context, ::sysinfo::ServerResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::sysinfo::Process>>(AsyncProcessesRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::sysinfo::Process>> PrepareAsyncProcesses(::grpc::ClientContext* context, ::sysinfo::ServerResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::sysinfo::Process>>(PrepareAsyncProcessesRaw(context, response, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Processes(::grpc::ClientContext* context, ::sysinfo::ServerResponse* response, ::grpc::ClientWriteReactor< ::sysinfo::Process>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientWriterInterface< ::sysinfo::Process>* ProcessesRaw(::grpc::ClientContext* context, ::sysinfo::ServerResponse* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::sysinfo::Process>* AsyncProcessesRaw(::grpc::ClientContext* context, ::sysinfo::ServerResponse* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::sysinfo::Process>* PrepareAsyncProcessesRaw(::grpc::ClientContext* context, ::sysinfo::ServerResponse* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientWriter< ::sysinfo::Process>> Processes(::grpc::ClientContext* context, ::sysinfo::ServerResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::sysinfo::Process>>(ProcessesRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::sysinfo::Process>> AsyncProcesses(::grpc::ClientContext* context, ::sysinfo::ServerResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::sysinfo::Process>>(AsyncProcessesRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::sysinfo::Process>> PrepareAsyncProcesses(::grpc::ClientContext* context, ::sysinfo::ServerResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::sysinfo::Process>>(PrepareAsyncProcessesRaw(context, response, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Processes(::grpc::ClientContext* context, ::sysinfo::ServerResponse* response, ::grpc::ClientWriteReactor< ::sysinfo::Process>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientWriter< ::sysinfo::Process>* ProcessesRaw(::grpc::ClientContext* context, ::sysinfo::ServerResponse* response) override;
    ::grpc::ClientAsyncWriter< ::sysinfo::Process>* AsyncProcessesRaw(::grpc::ClientContext* context, ::sysinfo::ServerResponse* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::sysinfo::Process>* PrepareAsyncProcessesRaw(::grpc::ClientContext* context, ::sysinfo::ServerResponse* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Processes_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Processes(::grpc::ServerContext* context, ::grpc::ServerReader< ::sysinfo::Process>* reader, ::sysinfo::ServerResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Processes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Processes() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Processes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Processes(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::sysinfo::Process>* /*reader*/, ::sysinfo::ServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcesses(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::sysinfo::ServerResponse, ::sysinfo::Process>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Processes<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Processes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Processes() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::sysinfo::Process, ::sysinfo::ServerResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, ::sysinfo::ServerResponse* response) { return this->Processes(context, response); }));
    }
    ~WithCallbackMethod_Processes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Processes(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::sysinfo::Process>* /*reader*/, ::sysinfo::ServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::sysinfo::Process>* Processes(
      ::grpc::CallbackServerContext* /*context*/, ::sysinfo::ServerResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Processes<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Processes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Processes() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Processes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Processes(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::sysinfo::Process>* /*reader*/, ::sysinfo::ServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Processes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Processes() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Processes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Processes(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::sysinfo::Process>* /*reader*/, ::sysinfo::ServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcesses(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Processes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Processes() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->Processes(context, response); }));
    }
    ~WithRawCallbackMethod_Processes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Processes(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::sysinfo::Process>* /*reader*/, ::sysinfo::ServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* Processes(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace sysinfo


#endif  // GRPC_info_2eproto__INCLUDED
